name: 'Autolink JIRA Issues'
description: 'Automatically links JIRA issues to the body of your PRs'
inputs:
  github-token:  # id of input
    description: 'Github api token if you want to fetch private repo'
    required: true
    default: ''
  issue-base-url:  # id of input
    description: 'URL to prepend to your JIRA ticket ID'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'